// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Anonymou
{
    public int IdAnonymous { get; set; }

    public string PlaceSale { get; set; }

    public DateTime? DateSale { get; set; }

    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();
}