// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Numerics;
using RPPP_WebApp.Util;


namespace RPPP_WebApp.Models;

public partial class Harvest
{

    public Harvest()
    {
        Workers = new HashSet<Worker>();
    }
    [DisplayName("Harvest ID"), Required(ErrorMessage = "Id Harvest is required")]
    public int IdHarvest { get; set; }


    [ExcelFormat("dd.mm.yyyy")]
    //[DisplayFormat(DataFormatString = "{0:dd.MM.yyyy.}", ApplyFormatInEditMode = true)]
    [DataType(DataType.Date)]
    [Display(Name = "Date")]
    [Required]
    public DateTime StartHarvest { get; set; }
    [ExcelFormat("dd.mm.yyyy")]
    //[DisplayFormat(DataFormatString = "{0:dd.MM.yyyy.}", ApplyFormatInEditMode = true)]
    [DataType(DataType.Date)]
    [Display(Name = "Date")]
    [Required]
    public DateTime EndHarvest { get; set; }

    public string UseHarvest { get; set; }

    public int QuantityHarvest { get; set; }
    [DisplayName("Cost Harvest"), Required(ErrorMessage = "Cost Harvest is required")]
    public int CostHarvest { get; set; }

    [DisplayName("Plant Name"), Required(ErrorMessage = "Id Plant is required")]
    public int IdPlant { get; set; }

    [DisplayName("Buyer Name")]
    public int? IdSale { get; set; }
    [DisplayName("Name Harvest"), Required(ErrorMessage = "Name Harvest is required")]
    public string NameHarvest { get; set; }

    public virtual Plant IdPlantNavigation { get; set; }

    public virtual Sale IdSaleNavigation { get; set; }

    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();

    public virtual ICollection<Worker> Workers { get; set; } = new List<Worker>();
}