// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace RPPP_WebApp.Models;

public partial class KnownCustomer
{
    [DisplayName("Person ID"), Required(ErrorMessage = "Id Person is required")]
    public int IdPerson { get; set; }

    public virtual Person IdPersonNavigation { get; set; }

    public virtual ICollection<Lease> Leases { get; set; } = new List<Lease>();

    public virtual ICollection<Request> Requests { get; set; } = new List<Request>();

    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();
}