// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Lease
{
    public int IdLease { get; set; }

    public string LeaseType { get; set; }

    public DateTime StardDate { get; set; }

    public DateTime? EndDate { get; set; }

    public int IdPerson { get; set; }

    public virtual KnownCustomer IdPersonNavigation { get; set; }

    public virtual ICollection<Plot> Plots { get; set; } = new List<Plot>();
}