// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace RPPP_WebApp.Models;

public partial class Person
{
    [DisplayName("Person ID  "), Required(ErrorMessage = "Person ID is required")]
    public int IdPerson { get; set; }
    [DisplayName("First Name "), Required(ErrorMessage = "First Name is required")]
    public string FirstName { get; set; }
    [DisplayName("Last Name "), Required(ErrorMessage = "Last Name is required")]
    public string LastName { get; set; }

    public string Address { get; set; }

    public string Number { get; set; }

    public string Mail { get; set; }

    public virtual KnownCustomer KnownCustomer { get; set; }

    public virtual Worker Worker { get; set; }

}
