// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using RPPP_WebApp.ViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace RPPP_WebApp.Models;

public partial class Plot
{   public Plot()
    {
        Plants = new HashSet<Plant>();

    }

    [DisplayName("Plot ID"), Required(ErrorMessage ="Id Plot is required")]
    public int IdPlot { get; set; }

    [DisplayName("Plot Name"), Required(ErrorMessage ="Plot name is required")]
    public string PlotName { get; set; }

    [DisplayName("Plot Gps"), Required(ErrorMessage = "Plot Gps is required")]
    public string PlotGps { get; set; }

    public string Infrastructure { get; set; }

    public string Material { get; set; }

    public int? SunIntensity { get; set; }

    public int? IdLease { get; set; }
    [DisplayName("IdSoil"), Required(ErrorMessage = "A soil is required")]
    public int IdSoil { get; set; }

    public virtual Lease IdLeaseNavigation { get; set; }

    public virtual Soil IdSoilNavigation { get; set; }

    public virtual ICollection<Plant> Plants { get; set; } 
}