// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Numerics;
using System.ComponentModel.DataAnnotations.Schema;

namespace RPPP_WebApp.Models;

public partial class Request
{
    public Request()
    {
    }
    [DisplayName("Request ID"), Required(ErrorMessage = "Id Request is required")]
    public int IdRequest { get; set; }

    [DisplayName("Species"), Required(ErrorMessage = "Species is required")]
    public string SpeciesAsked { get; set; }

    [DisplayName("Date"), Required(ErrorMessage = "Valide is required")]
    public DateTime DateRequest { get; set; }

    [DisplayName("Quantity"), Required(ErrorMessage = "Quantity is required")]
    public int QuantityAsked { get; set; }

    [DisplayName("Price"), Required(ErrorMessage = "Price is required")]
    public int PriceAsked { get; set; }

    public int? IdPerson { get; set; }

    [DisplayName("Status request"), Required(ErrorMessage = "Status request is required")]
    public string StatusRequest { get; set; }
    public virtual KnownCustomer IdPersonNavigation { get; set; }

}