// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Soil
{
    public int IdSoil { get; set; }

    public string SoilName { get; set; }

    public virtual ICollection<Plot> Plots { get; set; } = new List<Plot>();
}